[alias]
flash = "espflash flash --monitor"

[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Trom_functions.x",
]

[env]
ESP_LOGLEVEL = "info"

[unstable]
build-std = ["core"]